# Generated by Django 5.1.3 on 2024-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achieved', models.CharField(max_length=100)),
                ('showToSite', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('institution_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('showToSite', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='media/projects/')),
                ('link', models.URLField()),
                ('showToSite', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
            ],
        ),
    ]
